DjangoStore/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('products.urls', namespace='mainapp')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoStore/products/urls.py
from django.urls import path
from .views import Home, CategoryView, AllView, SearchView
from cart.views import add_to_cart, CartListView, increase_cart, decrease_cart, checkoutFormView, checkoutView
from orders.views import OrderCreateView, OrderCompleteView, OrderShowView, OrderDetailView, OrderFlush

app_name = 'mainapp'

urlpatterns = [
    path('', Home, name='home'),
    path('all', AllView, name='all'),
    path('search', SearchView, name='search'),
    path('orders/new', OrderCreateView, name='new-order'),
    path('list/<slug>', CategoryView, name='list'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('increase/<slug>', increase_cart, name='increase-cart'),
    path('decrease/<slug>', decrease_cart, name='decrease-cart'),
    path('cart/', CartListView.as_view(), name='cart-home'),
    path('checkout-form', OrderCreateView.as_view(), name='checkout-form'),
    path('orders/complete/<int:pk>', OrderCompleteView.as_view(), name='checkout'),
    path('orders/show', OrderShowView, name='orders-show'),
    path('orders/detail/<int:pk>', OrderDetailView, name='orders-detail'),
    path('orders/flush', OrderFlush, name='orders-purge')
]

DjangoStore/cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Product

User = get_user_model()

# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.quantity} of {self.item.name}'
        
    def get_total(self):
        total = self.item.price * self.quantity
        return total
        
    @classmethod
    def get_cart_quantity(cls,user):
        total_quantity = 0
        items = Cart.objects.filter(user=user)
        if items.exists():
            for item in items:
                total_quantity += item.quantity
        return total_quantity

    @classmethod
    def get_cart_sum(cls,user):
        sum = 0.0
        items = Cart.objects.filter(user=user)
        if items.exists():
            for item in items:
                sum += item.get_total()
        return sum

DjangoStore/orders/models.py
from datetime import datetime, timedelta
from django.db import models
from products.models import Product
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    orderdate = models.DateTimeField(auto_now_add=True, blank=True)
    shippingdate = models.DateTimeField(auto_now_add=True)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    province = models.CharField(max_length=50)
    postal_code = models.CharField(max_length=50)

    def __str__(self):
        return self.orderdate.strftime("%b.%d,%Y,%I:%M %p")

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()

DjangoStore/orders/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, ListView
from django.forms import ModelForm
from cart.models import Cart
from datetime import datetime, timedelta
from .models import Order, OrderItem
from django.http import HttpResponseForbidden
from django.contrib import messages

# Create your views here.

class OrderCreateForm(ModelForm):
    class Meta:
        model = Order
        fields = ['address','city','province','postal_code']
class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Order
    form_class = OrderCreateForm
    template_name = 'orders/order_create.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart_list'] = Cart.objects.filter(user=self.request.user)
        return context
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.instance.user = self.request.user
            form.instance.orderdate = datetime.now()
            form.instance.shippingdate = form.instance.orderdate + timedelta(days=3)
            form.save()

            cart_qs = Cart.objects.filter(user=self.request.user)
            if cart_qs.exists():
                for cart in cart_qs:
                    if cart.quantity > 0:
                        order_item, created = OrderItem.objects.get_or_create(order=form.instance, item=cart.item, defaults={'quantity': 0,'price':0},)
                    order_item.order = form.instance
                    order_item.item = cart.item
                    order_item.quantity = cart.quantity
                    order_item.price = cart.item.price
                    order_item.save()
                    cart.delete()

            return redirect('mainapp:checkout',pk=order_item.order.pk)
        return render(request, 'orders/order_create.html', {'form': form})
class OrderCompleteView(ListView):
    model = OrderItem
    context_object_name = 'order_list'
    template_name = 'orders/order_complete.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = Order.objects.get(pk=self.kwargs['pk'],user=self.request.user)
        context['order_list'] = OrderItem.objects.filter(order=order)
        return context
@login_required
def OrderShowView(request):
    Orders = Order.objects.filter(user=request.user)
    context = {'orders': Orders}
    return render(request, 'orders/order_show.html', context)
@login_required
def OrderDetailView(request, pk):
    order = Order.objects.get(pk=pk)
    if request.user != order.user:
        return HttpResponseForbidden()
    items = OrderItem.objects.filter(order=order)
    context= {'order': order, 'items': items}
    return render(request, 'orders/order_detail.html', context)
@login_required
def OrderFlush(request):
    orders = Order.objects.filter(user=request.user)
    orderItems = OrderItem.objects.filter(order__in=orders)
    if orders:
        for orderitem in orderItems:
            orderitem.delete()
        for order in orders:
            order.delete()
        messages.info(request, f"Your order history has been purged.")
    else:
        messages.info(request, f"You have no orders.")

    return redirect("mainapp:orders-show")

DjangoStore/templates/orders/order_complete.html
{% extends 'base.html' %}
{% block content %}
<div class=container>
    <div>
        <h2>
            THANK YOU FOR YOUR NON-EXISTENT ORDER
        </h2>
        <p5>
            seriously this is fake
        </p5>
    </div>
    <div class="container">
        <h4>
            Your order will be shipped to:
        </h4>
            {% for item in query %}
                <div>
                    <p3>{{ item }}</p3>
                </div>
            {% endfor %}
    </div>
    <div class="container my-5">
        <a href="{% url 'mainapp:home' %}" class="btn btn-success mr-4">GO BACK</a>
    </div>
</div>
{% endblock content %}

DjangoStore/templates/orders/order_create.html
{% extends 'base.html' %}
{% load cart_tag %}
{% block content %}
<h1>Check Out</h1>
<h2>Shipping Address</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success mr-4" value="Place Order">
</form>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Quantity</th>
            <th scope="col" style='text-align: right;'>Price</th>
        </tr>
    </thead>
    <tbody>
        {% for cart in cart_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ cart.item.name }}</td>
                <td>
                </td>

                <td style='text-align: right;'>$ {{ cart.get_total | floatformat:2 }} </td>
            </tr>
        {% endfor %}
        <tr>
            <th scope="row"></th>
            <td colspan="2">Total</td>

            <td style='text-align: right;'>${{ request.user | cart_total_sum | floatformat:2 }}</td>

        </tr>
    </tbody>
</table>
{% endblock content %}

DjangoStore/templates/orders/order_detail.html
{% extends 'base.html' %}
{% load cart_tag %}
{% block content %}
    <div class="container my-5">
        <div class="my-5">
            <h2>Your Order:</h2>
            <h5>Order Date: {{ order.orderdate }} Arrival Date: {{ order.shippingdate }}</h5>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Item</th>
                    <th scope="col">Quantity</th>
                    <th scope="col" style='text-align: right;'>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ item.item.name }}</td>
                    <td>
                        {{ item.quantity }}
                    </td>
                    <td style='text-align: right;'>$ {{ item.price }} </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

DjangoStore/templates/orders/order_show.html
{% extends 'base.html' %}
{% load cart_tag %}
{% block content %}
    <div class="container my-5">
        <div class="my-5">
            <h2>Your Orders</h2>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Order Date</th>
                    <th scope="col">Arrival Date</th>
                    <th scope="col" style='text-align: right;'>Detail View</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <th scope="row">Order {{ forloop.counter }}</th>
                        <td> 
                            Order Date:
                            {{ order.orderdate }}
                        </td>
                        <td> 
                            Arrival Date:
                            {{ order.shippingdate }}
                        </td>
                        <td colspan="3" class="text-right ">
                            <a href="{% url 'mainapp:orders-detail' order.pk %}" class="mr-4">Detail View</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <table>
            <thead>
                <tr>
                    <th scope="col" style='text-align: right;'><a href="{% url 'mainapp:orders-purge' %}">Purge Order History</a></th>
                </tr>
            </thead>
        </table>
    </div>
{% endblock content %}