DjangoStore/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('products.urls', namespace='mainapp')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoStore/products/urls.py
from django.urls import path
from .views import Home, CategoryView, AllView, SearchView
from cart.views import add_to_cart, CartListView, increase_cart, decrease_cart, checkoutFormView, checkoutView
from orders.views import OrderCreateView, OrderCompleteView, OrderShowView, OrderDetailView, OrderFlush

app_name = 'mainapp'

urlpatterns = [
    path('', Home, name='home'),
    path('all', AllView, name='all'),
    path('search', SearchView, name='search'),
    path('orders/new', OrderCreateView, name='new-order'),
    path('list/<slug>', CategoryView, name='list'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('increase/<slug>', increase_cart, name='increase-cart'),
    path('decrease/<slug>', decrease_cart, name='decrease-cart'),
    path('cart/', CartListView.as_view(), name='cart-home'),
    path('checkout-form', OrderCreateView.as_view(), name='checkout-form'),
    path('orders/complete/<int:pk>', OrderCompleteView.as_view(), name='checkout'),
    path('orders/show', OrderShowView, name='orders-show'),
    path('orders/detail/<int:pk>', OrderDetailView, name='orders-detail'),
    path('orders/flush', OrderFlush, name='orders-purge')
]

DjangoStore/products/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=300)
    primaryCategory = models.BooleanField(default=False)
    slug = models.SlugField(max_length=300, default=slugify(title))

    def __str__(self):
        return self.title

class Product(models.Model):
    mainimage = models.ImageField(upload_to='products/', blank=True)
    name = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300)
    featured = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Detail Text')
    price = models.FloatField()

    def __str__(self):
        return self.name

DjangoStore/products/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, FormView
from django.template import Context
from django.http import HttpResponseRedirect
from .models import Product, Category

# Create your views here.

def Home(request):
    products = Product.objects.filter(featured=True)
    context = {"all_products_list": list(products)}
    return render(request, 'products/home.html', context)

def CategoryView(request, slug):
    category = Category.objects.filter(slug=slug)[0]
    products = Product.objects.filter(category=category)
    context = {"all_products_list": list(products)}
    return render(request, 'products/home.html', context)

def AllView(request):
    products = Product.objects.all()
    context = {"all_products_list": list(products)}
    return render(request, 'products/home.html', context)

def SearchView(request):
    query = request.GET.get('q')
    products = Product.objects.filter(name__icontains=query)
    
    context = {"all_products_list": list(products)}

    return render(request, 'products/home.html', context)

DjangoStore/templates/products/home.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            {% for product in all_products_list %}
                <div class="col-md-4 col-sm-12 col-lg-3 m-1">
                    <div class="card" style='width:100%; '>
                        <img src= "media/{{ product.mainimage }}" style="width:100%;" class="card-img-top" alt="{{ product.name }}">
                        <div class="card-body">
                            <h6 class="card-title text-center"> {{ product.name }}</h6>
                            <p class="card-text text-center">${{ product.price }}</p>
                        </div>
                        <div class='card-footer text-center'>
                            <a href="{% url 'mainapp:cart' product.slug %}" class="btn btn-success">Add to Cart</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}