DjangoStore/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('products.urls', namespace='mainapp')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoStore/products/urls.py
from django.urls import path
from .views import Home, CategoryView, AllView, SearchView
from cart.views import add_to_cart, CartListView, increase_cart, decrease_cart, checkoutFormView, checkoutView
from orders.views import OrderCreateView, OrderCompleteView, OrderShowView, OrderDetailView, OrderFlush

app_name = 'mainapp'

urlpatterns = [
    path('', Home, name='home'),
    path('all', AllView, name='all'),
    path('search', SearchView, name='search'),
    path('orders/new', OrderCreateView, name='new-order'),
    path('list/<slug>', CategoryView, name='list'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('increase/<slug>', increase_cart, name='increase-cart'),
    path('decrease/<slug>', decrease_cart, name='decrease-cart'),
    path('cart/', CartListView.as_view(), name='cart-home'),
    path('checkout-form', OrderCreateView.as_view(), name='checkout-form'),
    path('orders/complete/<int:pk>', OrderCompleteView.as_view(), name='checkout'),
    path('orders/show', OrderShowView, name='orders-show'),
    path('orders/detail/<int:pk>', OrderDetailView, name='orders-detail'),
    path('orders/flush', OrderFlush, name='orders-purge')
]

DjangoStore/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
        <title> ultrCORE store | ultrcore.com </title>
    </head>
    <body>
        {% include 'navbar.html' %}

        <div class="container">
            <form action="{% url 'mainapp:search' %}" method="get">
                <input name="q" type="text" placeholder="Search...">
            </form>
        </div>
    
        {% if messages %}
            <div class="messages container mt-2">
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <main>
            <div class="container">
                {% block content %}
                {% endblock content %}
            </div>
        </main>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
</html>

DjangoStore/templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="btn btn-primary" href="/">PwA Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li {% if request.path == 'contact' %}class="nav-item active"{% else %}class="nav-item"{% endif %}>
                    <a class="nav-link" href="{% url 'mainapp:list' 'cpu' %}"> CPU <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:list' 'gpu' %}"> GPU </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:list' 'motherboard' %}"> Motherboards </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mainapp:all' %}">Show All Items</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="btn btn-primary" href="{% url 'mainapp:cart-home' %}">
                            <i class="fa fa-shopping-cart"></i> Cart <span class="badge badge-light">{{ request.user| cart_total_quantity }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="">
                            <i class="fas fa-user"></i> Hi {{ request.user.username }}!
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}"> Log Out</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mainapp:orders-show' %}">Your Orders</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="btn btn" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li><span>&nbsp;&nbsp;&nbsp;</span></li>
                    <li class="nav-item">
                        <a class="btn btn-primary" href="{% url 'signup' %}">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>