DjangoStore/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('products.urls', namespace='mainapp')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoStore/products/urls.py
from django.urls import path
from .views import Home, CategoryView, AllView, SearchView
from cart.views import add_to_cart, CartListView, increase_cart, decrease_cart, checkoutFormView, checkoutView
from orders.views import OrderCreateView, OrderCompleteView, OrderShowView, OrderDetailView, OrderFlush

app_name = 'mainapp'

urlpatterns = [
    path('', Home, name='home'),
    path('all', AllView, name='all'),
    path('search', SearchView, name='search'),
    path('orders/new', OrderCreateView, name='new-order'),
    path('list/<slug>', CategoryView, name='list'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('increase/<slug>', increase_cart, name='increase-cart'),
    path('decrease/<slug>', decrease_cart, name='decrease-cart'),
    path('cart/', CartListView.as_view(), name='cart-home'),
    path('checkout-form', OrderCreateView.as_view(), name='checkout-form'),
    path('orders/complete/<int:pk>', OrderCompleteView.as_view(), name='checkout'),
    path('orders/show', OrderShowView, name='orders-show'),
    path('orders/detail/<int:pk>', OrderDetailView, name='orders-detail'),
    path('orders/flush', OrderFlush, name='orders-purge')
]

DjangoStore/cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from products.models import Product

User = get_user_model()

# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'{self.quantity} of {self.item.name}'
        
    def get_total(self):
        total = self.item.price * self.quantity
        return total
        
    @classmethod
    def get_cart_quantity(cls,user):
        total_quantity = 0
        items = Cart.objects.filter(user=user)
        if items.exists():
            for item in items:
                total_quantity += item.quantity
        return total_quantity

    @classmethod
    def get_cart_sum(cls,user):
        sum = 0.0
        items = Cart.objects.filter(user=user)
        if items.exists():
            for item in items:
                sum += item.get_total()
        return sum

DjangoStore/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, View
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Cart
from products.models import Product
from django.contrib import messages

# Create your views here.
@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    cart, created = Cart.objects.get_or_create(
        item=item,
        user=request.user
    )
    if created:
        cart.quantity = 1
        cart.save()
        messages.info(request, f"{cart.item.name} has been added to your cart.")
    else:
        cart.quantity += 1
        cart.save()
        messages.info(request, f"{cart.item.name} quantity has been updated")

    return redirect("mainapp:home")
@login_required
def increase_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    cart_qs = Cart.objects.filter(user=request.user, item=item)
    if cart_qs.exists():
        cart = cart_qs[0]
        cart.quantity += 1
        cart.save()
        messages.info(request, f"{item.name} quantity has updated.")
    else:
        messages.warning(request, "This item was not in your cart")
    return redirect("mainapp:cart-home")

@login_required
def decrease_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    cart_qs = Cart.objects.filter(user=request.user, item=item)
    if cart_qs.exists():
        cart = cart_qs[0]
        # Checking the cart quantity
        if cart.quantity > 1:
            cart.quantity -= 1
            cart.save()
            messages.info(request, f"{item.name} quantity has updated.")
        else:
            cart.delete()
            messages.info(request, "This item was removed from your cart.")
    else:
        messages.warning(request, "This item was not in your cart")
    return redirect("mainapp:cart-home")

class CartListView(ListView, LoginRequiredMixin):
    model = Cart
    template_name = 'cart/home.html'
    context_object_name = 'cart_list'
    def get_queryset(self):
        return Cart.objects.filter(user=self.request.user)

@login_required
def checkoutFormView(request):
    cart = Cart.objects.filter(user=request.user)
    return render(request, 'cart/checkoutForm.html', {'cart_list': cart})

@login_required
def checkoutView(request):
    address = request.GET.get('address')
    city = request.GET.get('city')
    province = request.GET.get('province')
    postal_code = request.GET.get('postal-code')
    messages.info(request, "You have checked out your cart.")
    return render(request, 'cart/checkout.html', {'query': [address, city, province, postal_code]})

DjangoStore/templates/cart/checkout.html
{% extends 'base.html' %}
{% block content %}
<div class=container>
    <div>
        <h2>
            THANK YOU FOR YOUR NON-EXISTENT ORDER
        </h2>
        <p5>
            seriously this is fake
        </p5>
    </div>
    <div class="container">
        <h4>
            Your order will be shipped to:
        </h4>
            {% for item in query %}
                <div>
                    <p3>{{ item }}</p3>
                </div>
            {% endfor %}
    </div>
    <div class="container my-5">
        <a href="{% url 'mainapp:home' %}" class="btn btn-success mr-4">GO BACK</a>
    </div>
</div>
{% endblock content %}

DjangoStore/templates/cart/home.html
{% extends 'base.html' %}
{% load cart_tag %}
{% block content %}
    <div class="container my-5">
        <div class="my-5">
            <h2>Your Cart {{ request.user| cart_total_quantity }}</h2>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Product Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col" style='text-align: right;'>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for cart in cart_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ cart.item.name }}</td>
                        <td>                    
                            <a class="mr-2" href="{% url 'mainapp:decrease-cart' cart.item.slug %}"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
                            {{ cart.quantity }}
                            <a class="ml-2" href="{% url 'mainapp:increase-cart' cart.item.slug %}" ><span class="badge badge-light"><i class="fas fa-plus"></i></span></a>
                        </td>
                        <td style='text-align: right;'>$ {{ cart.get_total }} </td>
                    </tr>
                {% endfor %}
                <tr>
                    <th scope="row"></th>
                    <td colspan="2">Total</td>
                    <td style='text-align: right;'>{{ request.user | cart_total_sum | floatformat:2 }}</td>
                </tr>
                <tr>
                    <th scope="row"></th>
                    <td colspan="3" class="text-right ">
                        <button class="btn btn-success mr-4">Proceed To Checkout</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock content %}